name: tour_booking
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  http: ^1.2.2
  intl: ^0.18.0
  photo_view: ^0.15.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  provider: ^6.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_sign_in: ^6.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

